version: "3.7"

services:
  webserver:
    image: nginx:alpine
    container_name: project_webserver
    working_dir: /etc/nginx/conf.d
    ports:
      - 80:80
    volumes:
      - ${APP_PATH_HOST}/src:${APP_PATH_CONTAINER}
      - ${APP_PATH_HOST}/docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - php-fpm
    networks:
      - project
  php-fpm:
    container_name: project_php-fpm
    build: "docker/php-fpm/"
    working_dir: ${APP_PATH_CONTAINER}
    volumes:
      - ${APP_PATH_HOST}/src:${APP_PATH_CONTAINER}
    environment:
      XDEBUG_CONFIG: "remote_host=${DOCKER_INTERNAL_IP}"
    networks:
      - project
  db:
    container_name: project
    build: "docker/mysql/"
    working_dir: /var/www
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - project_data:${DB_PATH_CONTAINER}
    networks:
      - project
#  rebbitmq:
#    image: rabbitmq:3-management
#    container_name: project_rabbitmq
#    working_dir: /var/lib/rabbitmq
#    networks:
#        - project
#    volumes:
#        - project_rebbitmq_data:/var/lib/rabbitmq/mnesia/rabbit@project
#    environment:
#      - RABBITMQ_DEFAULT_USER=root
#      - RABBITMQ_DEFAULT_PASS=root
#    ports:
#      - "8081:5672"
#  redis:
#    container_name: project_redis
#    image: redis:latest
#    working_dir: /usr/local/etc/redis
#    ports:
#      - 6379:6379
#    volumes:
#      - project_redis_data:/usr/local/etc/redis
#    networks:
#      - project
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
#    container_name: project_elasticsearch
#    environment:
#      - xpack.security.enabled=false
#      - discovery.type=single-node
#    volumes:
#      - project_elasticsearch_data:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200
#      - 9300:9300
#    networks:
#      - project
networks:
  project:
    driver: bridge

volumes:
  project_data:
#  project_redis_data:
#  project_rebbitmq_data:
#  project_elasticsearch_data: